---
- name: Pulling opendaylight image
  kolla_docker:
    action: "pull_image"
    common_options: "{{ docker_common_options }}"
    image: "{{ opendaylight_image_full }}"
  when: inventory_hostname in groups['opendaylight']
