---
# enforce ironic usage only with openvswitch
- include: ironic-check.yml

- include: config.yml
  when: inventory_hostname in groups['compute']

- include: start.yml
  when: inventory_hostname in groups['compute']
